name: Playwright Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Playwright tests
        run: yarn unittest
